$api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

http:
  routers:
    ohmushi:
      service: ohmushi
      tls:
        certResolver: resolver

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  resolver:
    acme:
      storage: acme.json
      dnsChallenge:
        provider: ovh

tls:
  options:
    default:
      sniStrict: true
log:
  level: DEBUG
  filePath: "/var/log/traefik.log"

accessLog:
  filePath: "/var/log/access.log"
  format: json
